name: Update Scores

on:
  schedule:
    # Run at 6:00 PM UTC (12:00 PM CT)
    - cron: "0 18 * * *"
    # Run at 7:00 PM UTC (1:00 PM CT)
    - cron: "0 19 * * *"
    # Run at 8:00 PM UTC (2:00 PM CT)
    - cron: "0 20 * * *"
    # Run at 9:00 PM UTC (3:00 PM CT)
    - cron: "0 21 * * *"
    # Run at 10:00 PM UTC (4:00 PM CT)
    - cron: "0 22 * * *"
    # Run at 11:00 PM UTC (5:00 PM CT)
    - cron: "0 23 * * *"
    # Run at 12:00 AM UTC (6:00 PM CT)
    - cron: "0 0 * * *"
    # Run at 1:00 AM UTC (7:00 PM CT)
    - cron: "0 1 * * *"
    # Run at 2:00 AM UTC (8:00 PM CT)
    - cron: "0 2 * * *"
    # Run at 3:00 AM UTC (9:00 PM CT)
    - cron: "0 3 * * *"
    # Run at 4:00 AM UTC (10:00 PM CT)
    - cron: "0 4 * * *"
    # Run at 5:00 AM UTC (11:00 PM CT)
    - cron: "0 5 * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - run: python wjc.py
      - run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add scores.json
          git commit -m "Update scores" || echo "No changes"
          git push
